name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v12
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: Set up nixbuild.net
        uses: nixbuild/nixbuild-action@v11
        with:
          nixbuild_ssh_key: ${{ secrets.NIXBUILD_SSH_KEY }}
      - name: Build website
        run: nix build .#website
